# Generated by Django 4.2.7 on 2023-11-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_bag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag',
            old_name='user',
            new_name='reader_name',
        ),
    ]
