# Generated by Django 4.2.7 on 2023-11-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_rename_user_bag_reader_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='reader_name',
        ),
    ]
